### ISSUE TITLE
Let's find out the bug and resolve it!

### ISSUE THREAD

**Issue by jyeok** [swsnu/swpp2019-team10#106]
problem / the importance of problem 1~3 (in my opinion) 

1) Image load problem (3): We didn't implement properly the image handling part of frontend.
2) Main view problem (3):
  On `location`, It uses the outdated `reviewList` UI design.
  It doesn't filter the reviews by its distance from user.
3) Location view problem (3): On `reviewDetail`, the location of restaurant doesn't appear.
4) ReviewDetail UI problem (2): On `reviewDetail`, It uses the outdated `reviewList` tag design.
5) Upload Problem (3): Backend problem; It appears the backend cannot handle some specific input.
For input 'Good Good I love sour pizza. I like lemon.', the backend returns error:
`/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Good Good I love sour pizza. I like lemon.
Internal Server Error: /api/review/
Traceback (most recent call last):
  File "/home/jyeok/proj/team10/swpp2019-team10/backend/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/jyeok/proj/team10/swpp2019-team10/backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jyeok/proj/team10/swpp2019-team10/backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/jyeok/proj/team10/swpp2019-team10/backend/foodbook/foodbook_api/views/review_views.py", line 98, in review_list
    tags = Tagging(request.user.profile, menu, rating).tagging(content)
  File "/home/jyeok/proj/team10/swpp2019-team10/backend/foodbook/foodbook_api/algorithms/tagging.py", line 147, in tagging
    list_of_tags = self.tagging_for_recommend(text)
  File "/home/jyeok/proj/team10/swpp2019-team10/backend/foodbook/foodbook_api/algorithms/tagging.py", line 185, in tagging_for_recommend
    if adj == tag:
  File "/home/jyeok/proj/team10/swpp2019-team10/backend/foodbook/foodbook_api/algorithms/tagging.py", line 211, in __eq__
    return self.name.lemma == value.name.lemma and self.advmod.lemma == value.advmod.lemma
AttributeError: 'NoneType' object has no attribute 'lemma'`

6) Recommendation view problem (3)
 1. When we get reviews from `recommendation`, we can't see the `reviewDetail` of suggested restaurants.
 2. Recommendation by Location seems to broken; It doesn't show the list of restaurants.
 3. About `taste`, I cannot find the 'spicy' related keyword.

7) Edit problem (3): `Edit` don't works. It returns `400 Bad Request` instead.

8) Main problem (3): on `friend's main page`, the `location` and `category` view shows the user's reviews, not the `friend's reviews`.

**Comment by JaehoNam** [comment]
6-2 : our recommendation by loc is within 1km, so if you have no reviews in 1km then nothing is shown. 1km is somewhat short..!
8 : I will check it

**Comment by JaehoNam** [comment]
7 : At FormReview, frontend should post 'placeid' too.

**Comment by th-snu** [comment]
fixed 3 and 7 (followed Jaeho's note)
https://github.com/swsnu/swpp2019-team10/pull/108

**Comment by JaehoNam** [comment]
Bug

9. when Edit -> Submit -> Back, tagging is shown as default

**Comment by th-snu** [comment]
6-1: Recommendation components don't import reviewdetail at all, I think it isn't just added

**Comment by th-snu** [comment]
6. [When we get reviews from recommendation, we can't see the reviewDetail of suggested restaurants.]
7-2. [After editing a review, new content is not updated until the page is refreshed.]
are fixed

**Comment by jyeok** [comment]
All bugs I found is fixed; when you find any bug, write here!

**Comment by jyeok** [comment]
- [ ] When user types invalid friend url directly (ex: user types `/friend/1` when he has no friends) should redirect to `/main`

**Comment by jyeok** [comment]
-[] When user adds new reivew in `friend`'s home, the review will be shown (not actually added) at friend's home. In fact the add button itself should not appear in friend's home.

**Comment by jyeok** [comment]
- [ ] In `recommendationTag` the user's rating should be considered.

**Comment by jyeok** [comment]
- [ ] Remove solvable warnings of test

**Comment by jyeok** [comment]
> * [ ]  When user types invalid friend url directly (ex: user types `/friend/1` when he has no friends) should redirect to `/main`
It seems that the `friend` related code is written by @JaehoNam , this problem will be solved easily if @JaehoNam directly resolve this error.


> * [ ]  When user adds new reivew in `friend`'s home, the review will be shown (not actually added) at friend's home. In fact the add button itself should not appear in friend's home.
I made the main layout and view, I modified it to not render when the `friendId` is not equal to `-1`.


> * [ ]  In `recommendationTag` the user's rating should be considered.
The recommendation view of frontend is made by @JaehoNam  and @ByungHeeCha, so I left it! All other teammates are assigned to fixing bugs, so I think it is fair to pass to @ByungHeeCha .


> * [ ]  Remove solvable warnings of test
It seems that the warning messags appear after @th-snu made PR yesterday, I think this error should be handled by @th-snu .

**Comment by jyeok** [comment]
to @th-snu : please refer to my review at #115
